name: Generate Commits

on:
  workflow_dispatch: # Запуск вручную

jobs:
  generate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "kirkiiruch"
          git config user.email "kirillslyzhuck61@gmail.com"

      - name: Generate commits on selected dates
        run: |
          SELECTED_DATES=(
            "2024-01-02"
            "2024-01-04"
            "2024-01-08"
            "2024-01-14"
            "2024-01-20"
            "2024-02-01"
            "2024-02-05"
            "2024-02-11"
            "2024-02-24"
            "2024-03-03"
            "2024-03-05"
            "2024-03-15"
            "2024-03-22"
            "2024-04-01"
            "2024-04-04"
            "2024-04-15"
            "2024-04-25"
            "2024-05-05"
            "2024-05-10"
            "2024-05-18"
            "2024-05-31"
            "2024-06-07"
            "2024-06-20"
            "2024-07-01"
            "2024-07-03"
            "2024-07-18"
            "2024-08-01"
            "2024-08-10"
            "2024-08-21"
            "2024-09-02"
            "2024-09-04"
            "2024-09-15"
            "2024-09-26"
            "2024-10-01"
            "2024-10-13"
            "2024-10-25"
            "2024-11-04"
            "2024-11-11"
            "2024-11-21"
            "2024-12-01"
            "2024-12-09"
            "2024-12-20"
            "2024-12-31"
            "2025-01-10"
            "2025-01-15"
            "2025-01-28"
            "2025-02-02"
            "2025-02-14"
            "2025-02-25"
            "2025-03-06"
            "2025-03-14"
            "2025-03-27"
            "2025-04-02"
            "2025-04-13"
            "2025-04-20"
            "2025-04-29"
            "2025-05-03"
          )

          touch activity.txt

          for current_date in "${SELECTED_DATES[@]}"; do
            num_commits=$((RANDOM % 10 + 1))  # 🔥 от 1 до 10 коммитов
            for ((i=1; i<=num_commits; i++)); do
              hour=$(printf "%02d" $((RANDOM % 24)))
              minute=$(printf "%02d" $((RANDOM % 60)))
              second=$(printf "%02d" $((RANDOM % 60)))
              commit_date="${current_date}T${hour}:${minute}:${second}"

              echo "Commit $i for $commit_date" >> activity.txt

              git add activity.txt
              GIT_AUTHOR_DATE="$commit_date" GIT_COMMITTER_DATE="$commit_date" git commit --date="$commit_date" -m "Commit $i on $commit_date"
            done
          done

      - name: Push changes
        run: |
          git push origin main
